version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - ML_SERVICE_URL=http://cv:8001/predict
    depends_on:
      - cv

  cv:
    build: ./cv
    ports:
      - "8001:8001"

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

